apiVersion: v1
kind: Service
metadata:
  name: {{ include "search_service.fullname" . }}
  labels:
    {{- include "search_service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "search_service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
