apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: personalcook
  labels:
    app.kubernetes.io/name: search_service
    app.kubernetes.io/instance: search-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: search_service
    app.kubernetes.io/instance: search-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000